name: Jest Integration Tests

on:
  push:
    branches: [main, develop] # Adjust the branches as needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the Node.js version you need

      - name: Cache Node.js Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false --testPathPattern="path/to/changed/files"

      - name: Run tests in watch mode
        run: npm test -- --watch

      - name: Generate Code Coverage Report
        run: npm run coverage

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/

      - name: Fail Fast on Test Failures
        if: failure()
        run: exit 1

      - name: Notify Team on Test Failures
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: your-slack-channel # Replace with your Slack channel name
          SLACK_COLOR: ${{ job.status }} # Use the job status for the color (e.g., danger for failure)
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_TITLE: Jest Integration Tests Failed
          SLACK_USERNAME: GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} # Replace with your Slack webhook URL