name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]  # Specify your Node.js version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Set up CODECOV_TOKEN in your repository secrets
          files: coverage/clover.xml  # Adjust the path if needed

      - name: Fail if coverage is below threshold
        run: |
          THRESHOLD=90
          COVERAGE=$(cat coverage/clover.xml | grep -oP '(?<=<coverage[^>]*>)[^<]*(?=</coverage>)')
          if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
            echo "Code coverage ($COVERAGE%) is below the threshold ($THRESHOLD%)"
            exit 1
          fi

      - name: Send Slack notification on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: your-slack-channel  # Replace with your Slack channel
          SLACK_COLOR: '#FF0000'  # Red color for failure
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_MESSAGE: 'Integration tests failed on ${{ github.ref }}'
          SLACK_TITLE: 'CI Failure'
          SLACK_USERNAME: GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}  # Set up SLACK_WEBHOOK in your repository secrets